V8.x - Update library to use serato/jwt 3.0
serato/web-sws-php-bootstrap pull request #108
Opened 2024-06-17 01:17 UTC by Mike-Serato

- Was unsure why a Memcached instance was required to bootstrap the library when a PSR Cache Pool should be enough? Let me know if I am missing anything.
- Updated unit tests for Access token middleware.
- Also includes some cleanup like adding return types, updating Docblocks etc.

2024-06-17 02:19 UTC, jordan-chen-serato requested changes

2024-06-17 02:19 UTC, jordan-chen-serato commented on src/Slim/Middleware/AccessScopes/AccessToken.php
>       * @var Sdk
Should change the comment.

2024-06-17 02:19 UTC, jordan-chen-serato commented on src/Slim/Middleware/AccessScopes/AccessToken.php
>       * Get the AWS Sdk
Change the comment

2024-06-17 02:19 UTC, jordan-chen-serato commented on src/Slim/Middleware/AccessScopes/AccessToken.php
>  use Aws\Sdk;
Do we still need this?

2024-06-17 02:19 UTC, jordan-chen-serato commented on src/Slim/Middleware/AccessScopes/ClientAppBasicAuth.php
> +     * @return mixed
Is this intended?

2024-06-17 02:32 UTC, Mike-Serato commented on src/Slim/Middleware/AccessScopes/ClientAppBasicAuth.php
> +     * @return mixed
Yes, it is. $next is a callable.

2024-06-17 22:15 UTC, harrietrc approved these changes
Looks great! I agree that the Memcached instance isn't necessary. It looks like it was redundant before, and Chris has switched to using `CacheItemPoolInterface::getIem()` in place of `Memcached::get()` everywhere in the new release.

2024-06-18 21:55 UTC, jordan-chen-serato approved these changes

2024-06-30 22:42 UTC, merged